### ISSUE TITLE
No Geupsik Informatiin

### ISSUE THREAD

**Issue by MareNectaris** [Party4Bread/SchoolInfoBringer#2] opened 2018-03-27 23:20 UTC
![capture](https://user-images.githubusercontent.com/30724686/38000201-6b89e03e-3261-11e8-8342-e6883cce4d45.PNG)
plz solve dis 'tank' you

**Comment by Party4Bread** [comment] 2018-03-28 08:25
Duplicate of #1

**Closed as completed by Party4Bread** 2018-03-28 08:25 UTC
